---
title: "RWorksheet_Huervana3b"
output: pdf_document
date: "2023-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo = TRUE} 
#1. A Create a data frame using the table below.

resp <- c(1:20)
sex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
occu <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
persHome <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
sib <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
houseType <- c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)


householdData <- data.frame(
  Respondents = resp,
  Sex = sex,
  FatherOccupation = occu,
  PersonAtHome = persHome,
  SiblingsAtSchool = sib,
  HouseType = houseType
)
householdData

#1  B

str(householdData)
summary(householdData)

#You have a table with 20 rows and 6 columns. The columns are:

#Respondents: A number that identifies each person.
#Sex: Tells if the person is a male (1) or female (2).
#Father's Occupation:  indicates the father's occupation .
#Persons at Home: Indicates how many people are in the person's home.
#Siblings at School: Tells you how many siblings of the person are going to school.
#Type of House: describes the type of house  

#1.C Is the mean number of siblings attending is 5?
sibsMean <- mean(householdData$SiblingsAtSchool)

sibsMean

# the mean of the number of siblings at school is 2.95, which is not 5

#1.D Extract the 1st two rows and then all the columns using the subsetting functions.
firstTwoRows <- householdData[1:2,]
firstTwoRows

#1.E Extract 3rd and 5th row with 2nd and 4th column.
thirdAndFifthRows <- householdData[c(3,5),c(2,4)]
thirdAndFifthRows


#1.F Select the variable types of houses then store the vector that results as types_houses.
types_houses <- householdData$HouseType
types_houses


#1.G Select only all Males respondent that their father occupation was farmer.
maleFarmer <- householdData[householdData$Sex == 1 & householdData$FatherOccupation == 1,]

maleFarmer

# there are no observations

#1.H Select only all females respondent that have greater than or equal to 5 number of siblings attending school.

femaleResp <- householdData[householdData$SiblingsAtSchool >= 5,]

femaleResp

# It shows 5 observations

# ------------------------------------

# 2 Write a R program to create an empty data frame.
df = data.frame(Ints=integer(),
Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE
)

print("Structure of the empty dataframe:")
print(str(df))

#You have an empty data table with no rows and 5 columns. 

#These columns have different data types:
#ints: They can hold whole numbers (integers).
#doubles: They can store decimal numbers.
#characters: These columns can hold text or words.
#logicals: They can store either "true" or "false" values.
#factors: These are used to categorize data but currently have no categories (0 levels), so they're essentially empty.
#This table is like a template and can be filled with data later.



# 3 Create a .csv file of this. Save it as HouseholdData.csv

newResp <- c(1:10)
newSex <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male")
newOcc <- c(1,2,3,3,1,2,2,3,1,3)
newPersonsAtHome <- c(5,7,3,8,6,4,4,2,11,6)
newSib <- c(2,3,0,5,2,3,1,2,6,2)
newType <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

HouseholdData <- data.frame(
  Respondents = newResp,
  Sex = newSex,
  FatherOccupation = newOcc,
  PersonAtHome = newPersonsAtHome,
  SiblingsAtSchool = newSib,
  HouseType = newType
)

write.csv(HouseholdData, file = "HouseholdData.csv")

#3 A Import the csv file into the R environment.

imported <-  read.csv("HouseholdData.csv")
imported

#3 B Convert the Sex into factor using factor() function and change it into integer.[Legend: Male = 1 and Female = 2].

imported$Sex <- factor(imported$Sex, levels = c("Male", "Female"))
imported$Sex <- as.integer(imported$Sex)

imported$Sex

#3 C Convert the Type of Houses into factor and change it into integer. [Legend: Wood = 1; Congrete = 2; Semi-Congrete = 3].

imported$HouseType <- factor(imported$HouseType, levels = c("Wood", "Congrete", "Semi-congrete"))
imported$HouseType <- as.integer(imported$HouseType)

imported$HouseType

#3 D On father’s occupation, factor it as Farmer = 1; Driver = 2; and Others = 3.

imported$FatherOccupation <- factor(imported$FatherOccupation, levels = c(1,2,3), labels = c("Farmer", "Driver", "Others"))

imported$FatherOccupation

#3 E Select only all females respondent that has a father whose occupation is driver.

femaleDriver <- imported[imported$Sex == 2 & imported$FatherOccupation == "Driver",]
femaleDriver

#3 F Select the respondents that have greater than or equal to 5 number of siblings attending school.

greaterFive <- imported[imported$SiblingsAtSchool >= 5,]
greaterFive


#4 Interpret the graph.


# Based on this data, we can infer that public sentiment is influenced by external events or circumstances, and it fluctuates from day to day in response to these factors.


```