---
title: "RWorksheet_Huervana#3"
output: pdf_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo = TRUE}

LETTERS

letters

#1 A Produce a vector that contains the first 11 letters.


  LETTERS1to11 <- LETTERS[c(1:11)]
  LETTERS1to11
  
#1 B Produce a vector that contains the odd numbered letters.
  
  lengthlet <- length(LETTERS)
  odd_letters <- LETTERS[seq(lengthlet) %% 2 == 1]
  odd_letters

  
#1 C Produce a vector that contains the vowels.

  vowelsLETTERS <- LETTERS[c(1,5,9,15,21)]
  vowelsLETTERS
  
  
#1 D Produce a vector that contains the last 5 lowercase letters.
  
  letters
  last5 <- letters[c(22:26)]
  last5


#1 E Produce a vector that contains letters between 15 to 24 letters in lowercase.
  
  fifto24 <- letters[c(15:24)]
  fifto24
  
  
# 2 A Create a vector
  
  city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
  city
  
#2 B  The average temperatures in Celcius
  
  temp <- c(42, 39, 34, 34, 30, 27)
  temp
  
#2 C Create a dataframe to combine the city and the temp
  
 cityTemp <- data.frame(city,temp)
  cityTemp

  
# 2 D Associate the dataframe you have created in 2.(c)
  
  names(cityTemp) <- c("City", "Temperature")
  cityTemp
  

# 2 E Print the structure by using str() function. Describe the output.
    
  str(cityTemp)
  # cityTemp is displayed
  # It displays the content and summary of the data frame.
 
# 2 F From the answer in d, what is the content of row 3 and row 4
  
  twoRows <- cityTemp[3:4,]
  twoRows

# 2 G From the answer in d, display the city with highest temperature and the city wit the lowest temperature.
  
  highTemp <- cityTemp[which.max(cityTemp$Temperature),]
  highTemp


  lowTemp <- cityTemp[which.min(cityTemp$Temperature),]
  lowTemp

  
  
  
  
## Using Matrices
  

  
# 2 A Create a matrix of one to eight and eleven to fourteen with four columns and three rows.

  matrix <- matrix(c(1:8,11:14), nrow = 3, ncol = 4)
  matrix
  
#2 B Multiply the matrix by two.
  
  mulMatrix <- matrix * 2
  mulMatrix
  
#2 C What is the content of row 2?
  
  rowTwo <- mulMatrix[2,]
  rowTwo
  
#2 D What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2?
  
  twoCols_Rows <- mulMatrix[c(1,2),c(3,4)]
  twoCols_Rows
  
#2 E What is the R code is you want to display only the columns in 2 and 3, row 3?
  
  twoColsRow <- mulMatrix[3,c(2,3)]
  twoColsRow

#2 F What is the R code is you want to display only the columns 4?
  
  fourCols <- mulMatrix[,4]
  fourCols
  
# 2 G Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.‘.
  
  dimnames(mulMatrix) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))
  mulMatrix
  
# 2 F From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim(). New dimensions should have 2 columns and 6 rows.
  
  matrix
  dim(matrix) <- c(6,2)
  matrix
  
  
  
## Arrays
  
  
  
# 3  An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1 
  
#3 A Create an array for the above numeric values. Each values will be repeated twice
  
  numValues <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
  repValues <- rep(numValues, each = 2)

  arr <- array(repValues, dim = c(2,4,3))
  arr
  
#3 B How many dimensions do your array have?
  # 3
  
# 3 c Name the rows as lowercase letters and columns as uppercase letters starting from the A.
  
  dimnames(arr) <- list(
  
  letters[1:2], 
  LETTERS[1:4], 
  c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array") 
)
  
  arr
  
```
